
BTFW.define("feature:gifs", ["feature:chat"], async ({}) => {
  const GIPHY_KEY = "bb2006d9d3454578be1a99cfad65913d";
  const TENOR_KEY = "5WPAZ4EXST2V";
  function ensureModal(){ if(document.getElementById("btfw-gif-modal")) return; const m=document.createElement("div"); m.id="btfw-gif-modal"; m.className="modal"; m.innerHTML=`<div class="modal-background"></div><div class="modal-card" style="width:min(980px,92vw);max-height:88vh;"><header class="modal-card-head"><p class="modal-card-title">GIFs</p><button class="delete" aria-label="close"></button></header><section class="modal-card-body"><div class="tabs is-boxed is-small"><ul><li class="is-active" data-tab="giphy"><a>Giphy</a></li><li data-tab="tenor"><a>Tenor</a></li></ul></div><div class="field has-addons" style="margin-bottom:10px;"><div class="control is-expanded"><input id="btfw-gif-q" class="input" placeholder="Search GIFs…"></div><div class="control"><button id="btfw-gif-search" class="button is-info is-light">Search</button></div><div class="control"><button id="btfw-gif-trending" class="button is-dark is-light">Trending</button></div></div><div class="content" id="btfw-gif-panes"><div class="pane" data-pane="giphy"></div><div class="pane is-hidden" data-pane="tenor"></div></div></section></div>`; document.body.appendChild(m); m.querySelector(".delete").onclick=hide; m.querySelector(".modal-background").onclick=hide; m.querySelectorAll(".tabs li").forEach(li=>li.onclick=()=>switchTab(li.dataset.tab)); m.querySelector("#btfw-gif-search").onclick=()=>perform(false); m.querySelector("#btfw-gif-trending").onclick=()=>perform(true); }
  function switchTab(tab){ document.querySelectorAll("#btfw-gif-modal .tabs li").forEach(li=>li.classList.toggle("is-active", li.dataset.tab===tab)); document.querySelectorAll("#btfw-gif-panes .pane").forEach(p=>p.classList.toggle("is-hidden", p.dataset.pane!==tab)); }
  function show(){ ensureModal(); document.getElementById("btfw-gif-modal").classList.add("is-active"); perform(true); }
  function hide(){ const m=document.getElementById("btfw-gif-modal"); if(m) m.classList.remove("is-active"); }
  function trimGif(u){ return (u||"").split("?")[0]; }
  function insertText(text){ const line=document.getElementById("chatline"); if(!line) return; const s=line.selectionStart||line.value.length; const e=line.selectionEnd||line.value.length; line.value=line.value.slice(0,s)+text+line.value.slice(e); line.focus(); line.setSelectionRange(s+text.length,s+text.length); }
  async function perform(trending){ ensureModal(); const q=document.getElementById("btfw-gif-q").value.trim(); const active=document.querySelector("#btfw-gif-modal .tabs li.is-active").dataset.tab; const pane=document.querySelector(`#btfw-gif-panes .pane[data-pane="${active}"]`); pane.innerHTML="<p>Loading…</p>"; try{ if(active==="giphy"){ const base="https://api.giphy.com/v1/gifs/"; const ep=trending?"trending?limit=50":("search?q="+encodeURIComponent(q||"funny")+"&limit=50"); const res=await fetch(base+ep+"&api_key="+GIPHY_KEY,{mode:"cors"}); const data=await res.json(); const list=(data.data||[]).map(d=>trimGif(d.images?.downsized?.url||d.images?.original?.url)); render(list,pane);} else { const base="https://api.tenor.com/v1/"; const url=trending?(base+"trending?key="+TENOR_KEY+"&limit=50"):(base+"search?key="+TENOR_KEY+"&q="+encodeURIComponent(q||"funny")+"&limit=50"); const res=await fetch(url,{mode:"cors"}); const data=await res.json(); const list=(data.results||[]).map(r=>trimGif(r.media?.[0]?.gif?.url)); render(list,pane);} }catch(e){ pane.innerHTML="<p>Failed to load GIFs.</p>"; } }
  function render(urls,pane){ const g=document.createElement("div"); g.className="columns is-multiline is-mobile"; (urls||[]).filter(Boolean).slice(0,48).forEach(u=>{ const col=document.createElement("div"); col.className="column is-one-quarter-desktop is-one-third-tablet is-half-mobile"; const b=document.createElement("button"); b.className="button is-dark is-light"; b.style.padding="0"; b.style.width="100%"; b.innerHTML=`<img loading="lazy" src="${u}" style="display:block;width:100%;height:auto;border-radius:8px;">`; b.onclick=()=>{ insertText(u+" "); hide(); }; col.appendChild(b); g.appendChild(col); }); pane.innerHTML=""; pane.appendChild(g); }
  document.addEventListener("btfw:openGifs", show);
  return {name:"feature:gifs"};
});
